version = 1

[[analyzers]]
name = "test-coverage"
enabled = true
  [analyzers.meta]
  coverage_path = [
    "$DashCam!/**/*.lcov",
    "src/**/*.lcov",
    "src/**/*.info" 
  ]
  coverage_format = "lcov"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = [
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "swift-format"
