version = 1

[[analyzers]]
name = "test-coverage"
enabled = true
  [analyzers.meta.reports.swift]
  coverage_path = "$DashCam!/coverage.lcov"
  coverage_format = "lcov"

  [analyzers.meta.reports.js-ts]
  coverage_path = "src/coverage/lcov.info"
  coverage_format = "lcov"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = [
    "nodejs",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "swift-format"
