# Wrangler configuration for Cloudflare Pages.
# Deploy with `npx wrangler pages deploy dist --project-name <your-project-name>`.

name = "template-portfolio"
compatibility_date = "2024-05-17"
pages_build_output_dir = "dist"
build_command = "npm run build:pages"

# Uncomment to surface non-sensitive environment variables when needed.
# [vars]
# VITE_PAGECLIP_API_KEY = ""
# VITE_TURNSTILE_SITE_KEY = ""
# VITE_TURNSTYLE_SITE = ""
