name: e2e-screenshot

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (takes screenshot)
        run: npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-screenshot
          path: |
            playwright-logs/portfolio-working.png
            playwright-report/**

      - name: Comment on PR with inline screenshot
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v1
        with:
            message: |
              **Web Preview**

              ![Playwright Screenshot][screenshot]

              _This screenshot was generated by Playwright during the latest workflow run._
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            allow-repeats: false
            images: |
              playwright-logs/portfolio-working.png



      # Optional: mark older bot comments as outdated
      - name: Find previous screenshot comments
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@v3
        id: find_comments
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Automated Playwright Screenshot'

      - name: Outdate previous screenshot comment
        if: steps.find_comments.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comments.outputs.comment-id }}
          body: '[OUTDATED] See the latest comment above.'
