name: e2e-screenshot

permissions:
  contents: read
  pull-requests: write
  issues: write
  # Needed to push to gh-pages from same-repo PRs/pushes
  pages: write

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (takes screenshot)
        run: npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-screenshot
          path: |
            playwright-logs/portfolio-working.png
            playwright-report/**

      - name: Add screenshot to job summary
        run: |
          if [ -f playwright-logs/portfolio-working.png ]; then
            echo "## Automated Playwright Screenshot" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "![Playwright Screenshot](playwright-logs/portfolio-working.png)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "_This screenshot was generated by Playwright during the latest workflow run._" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Screenshot not found." >> $GITHUB_STEP_SUMMARY
          fi

      # Prepare a folder to publish to gh-pages
      - name: Prepare gh-pages payload
        id: prep_pages
        run: |
          mkdir -p _screenshot_publish/screenshots/${{ github.run_id }}
          if [ -f playwright-logs/portfolio-working.png ]; then
            cp playwright-logs/portfolio-working.png _screenshot_publish/screenshots/${{ github.run_id }}/portfolio-working.png
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      # Publish to gh-pages ONLY for same-repo events (forks can't push)
      - name: Publish screenshot to gh-pages
        if: steps.prep_pages.outputs.found == 'true' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_screenshot_publish
          keep_files: true
          allow_empty_commit: false
          commit_message: "docs(screenshot): ${{ github.run_id }}"

      # Comment inline with the hosted image (same-repo PRs/pushes)
      - name: Comment on PR with inline screenshot (gh-pages URL)
        if: steps.prep_pages.outputs.found == 'true' && github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const runId = process.env.GITHUB_RUN_ID;

            // GitHub Pages URL shape: https://<owner>.github.io/<repo>/screenshots/<run_id>/portfolio-working.png
            const imageUrl = `https://${owner}.github.io/${repo}/screenshots/${runId}/portfolio-working.png`;

            const body = [
              '**Web Preview**',
              '',
              `![Playwright Screenshot](${imageUrl})`,
              '',
              '_This screenshot was generated by Playwright during the latest workflow run._'
            ].join('\n');

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.issue.number,
              body
            });

      # Fallback for forked PRs: comment with a summary link (can’t push to gh-pages)
      - name: Comment on PR (fork fallback)
        if: github.ev
